### ISSUE TITLE
Regression in 'components/pascal/data/xquery_module_file.pas'

### ISSUE THREAD

**Issue by Reino17** [benibela/xidel#50]
Ever since [`5791:69a4877c5433`](https://sourceforge.net/p/videlibri/code/ci/69a4877c5433) (or [`5793:500b6703549a`](https://sourceforge.net/p/videlibri/code/ci/500b6703549a) being the first to compile without errors), or `xidel-0.9.9.20200301.7232.bb3d69a31dfd`, `file:list()` and `file:read-binary()` don't work anymore:

```
xidel -se 'file:list(.)'
Error:
err:XPST0017: unknown function: file:list #1
[...]

xidel -se 'file:read-binary("test.txt")'
Error:
err:XPST0017: unknown function: file:read-binary #1
```

**Comment by benibela** [comment]
fixed

**Comment by Reino17** [comment]
I noticed you pushed A LOT of commits in only 2 weeks time. Very impressive!

However, I'm afraid this commit doesn't fix this issue. I'm still getting `err:XPST0017: unknown function: file:list #1`.  
And yes, my binary is from [`5956:aeb575175d5d`](https://sourceforge.net/p/videlibri/code/ci/aeb575175d5d).

**Comment by benibela** [comment]
>I noticed you pushed A LOT of commits in only 2 weeks time. Very impressive!

I was having a vacation

But it is has ended now
